#开启sentinel对feign的支持
#feign.sentinel.enabled: true
feign.client.config.default.connectTimeout: 10000
feign.client.config.default.readTimeout: 10000
spring:
  zipkin:
    base-url: http://192.168.105.71:9411/
    sender.type: web
  #采样比例默认的为 0.1可设置介于 0到 1之间，1则表示全部采集
  sleuth.sampler.probability: 0.1
  cloud.alibaba.seata.tx-service-group: business-service
seata:
  enabled: true
  service:
    grouplist.default: 192.168.105.71:8091
    vgroup-mapping.business-service: default
    disable-global-transaction: false